name: mermaid ci

on:
  push:
    branches:
      - main
      
jobs:
  mermaid-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup node action
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"      
      
      - name: Install dependencies
        run: npm install
    
      - name: Generate diagram
        run: npx generate-diagram -- -i 'diagram-2022-09-06 14_21_17.md' -o diagram.svg
        
      - name: Upload svg in artifcat
        uses: actions/upload-artifact@v3
        with:
          name: diagram-svg
          path: diagram-1.svg
        
          
