name: mermaid ci

on:
  push:
    branches:
      - main
      
jobs:
  mermaid-test:
    name: Mermaid test
    runs-on: ubuntu-latest
    
    steps:
      - name: Run mermaid test
        run: cat diagram-2022-09-06 14_21_17.md >> $GITHUB_STEP_SUMMARY
