name: mermaid ci

on:
  push:
    branches:
      - main
      
jobs:
  mermaid-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup node action
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"      
    
      - name: Install mermaid dependency
        run: npm install -g @mermaid-js/mermaid-cli
        
      - name: Run mermaid convertion
        run: |
          mmdc -i 'diagram-2022-09-06 14_21_17.md' -o mermaid.svg
          cat mermaid.svg >> $GITHUB_STEP_SUMMARY
